export const GET_DECK_SUCCESS = "GET_DECK_SUCCESS";
export const RESET_GAME = "RESET_GAME";
export const DRAW_CARDS_FOR_PLAYERS = "DRAW_CARDS_FOR_PLAYERS";
export const UPDATE_SCORE = "UPDATE_SCORE";
